version: 1.0.0.{build}
branches:
  only:
  - master
 install:
- git submodule update --init --recursive
build_script:
- Prebuild.exe /target vs2015 /targetframework v4_6 /conditionals ISWIN;NET_4_6
- msbuild Universe.sln /p:Configuration=Debug  /p:DefineConstants="ISWIN;NET_4_6"
artifacts:
- path: VirtualUniverse\bin
  name: Universe